version: '3.1'

services:
  app:
    container_name: nest_api_dev
    build: 
      context: .
      target: development
      dockerfile: ./Dockerfile
    
    volumes:
      - ./:/usr/app

    ports:
      - 3000:3000

    command: npm run start:dev